// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: npl.proto

/*
Package go_micro_srv_npl is a generated protocol buffer package.

It is generated from these files:
	npl.proto

It has these top-level messages:
	NplResponse
	Participle
	SentenceRequest
*/
package go_micro_srv_npl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for NplService service

type NplService interface {
	GetParticiple(ctx context.Context, in *SentenceRequest, opts ...client.CallOption) (*NplResponse, error)
}

type nplService struct {
	c    client.Client
	name string
}

func NewNplService(name string, c client.Client) NplService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.npl"
	}
	return &nplService{
		c:    c,
		name: name,
	}
}

func (c *nplService) GetParticiple(ctx context.Context, in *SentenceRequest, opts ...client.CallOption) (*NplResponse, error) {
	req := c.c.NewRequest(c.name, "NplService.GetParticiple", in)
	out := new(NplResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NplService service

type NplServiceHandler interface {
	GetParticiple(context.Context, *SentenceRequest, *NplResponse) error
}

func RegisterNplServiceHandler(s server.Server, hdlr NplServiceHandler, opts ...server.HandlerOption) error {
	type nplService interface {
		GetParticiple(ctx context.Context, in *SentenceRequest, out *NplResponse) error
	}
	type NplService struct {
		nplService
	}
	h := &nplServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NplService{h}, opts...))
}

type nplServiceHandler struct {
	NplServiceHandler
}

func (h *nplServiceHandler) GetParticiple(ctx context.Context, in *SentenceRequest, out *NplResponse) error {
	return h.NplServiceHandler.GetParticiple(ctx, in, out)
}
